language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
sudo: false
script: make
